export const locations = [
  {id: 1, title: 'India', country: 'USA', selected: false},
  {id: 2, title: 'USA', country: 'India', selected: false},
  {id: 3, title: 'Japan', country: 'Japan', selected: false},
  {id: 4, title: 'Spain', country: 'Spain', selected: false},
  {id: 5, title: 'France', country: 'Spain', selected: false},
  {id: 6, title: 'Germany', country: 'Spain', selected: false},
  {id: 7, title: 'Italy', country: 'Spain', selected: false},
  {id: 8, title: 'Canada', country: 'France', selected: false},
  {id: 9, title: 'Australia', country: 'Germany', selected: false},
  {id: 10, title: 'China', country: 'Germany', selected: false},
  {id: 11, title: 'Brazil', country: 'USA', selected: false},
  {id: 12, title: 'United Kingdom', country: 'USA', selected: false},
  {id: 13, title: 'Russia', country: 'USA', selected: false},
  {id: 14, title: 'Mexico', country: 'USA', selected: false},
  {id: 15, title: 'Argentina', country: 'USA', selected: false},
  {id: 16, title: 'South Korea', country: 'Japan', selected: false},
  {id: 17, title: 'Saudi Arabia', country: 'Spain', selected: false},
  {id: 18, title: 'South Africa', country: 'Spain', selected: false},
  {id: 19, title: 'Nigeria', country: 'Spain', selected: false},
  {id: 20, title: 'Netherlands', country: 'Spain', selected: false},
  {id: 21, title: 'Switzerland', country: 'Spain', selected: false},
  {id: 22, title: 'Sweden', country: 'Spain', selected: false},
  {id: 23, title: 'Belgium', country: 'France', selected: false},
  {id: 24, title: 'Norway', country: 'Germany', selected: false},
  {id: 25, title: 'Austria', country: 'Germany', selected: false},
  {id: 26, title: 'Denmark', country: 'Germany', selected: false},
  {id: 27, title: 'Poland', country: 'Germany', selected: false},
  {id: 28, title: 'Turkey', country: 'Germany', selected: false},
  {id: 29, title: 'Thailand', country: 'Germany', selected: false},
  {id: 30, title: 'Egypt', country: 'Germany', selected: false},
  {id: 31, title: 'Greece', country: 'Germany', selected: false},
  {id: 32, title: 'Portugal', country: 'Germany', selected: false},
  {id: 33, title: 'Ukraine', country: 'Germany', selected: false},
  {id: 34, title: 'Hungary', country: 'Germany', selected: false},
  {id: 35, title: 'Vietnam', country: 'Germany', selected: false},
  {id: 36, title: 'Israel', country: 'Germany', selected: false},
  {id: 37, title: 'Iraq', country: 'Germany', selected: false},
  {id: 38, title: 'Iran', country: 'Germany', selected: false},
  {id: 39, title: 'Pakistan', country: 'Germany', selected: false},
  {id: 40, title: 'Bangladesh', country: 'Germany', selected: false},
];
