import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  thumbnailView: {
    marginTop: 20,
    height: 198,
    width: '100%',
    backgroundColor: color.deactivatedBG,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 1.5,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  thumbnail: {
    flex: 1,
    height: 198,
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  uploadVideoText: {
    marginLeft: 6,
    fontFamily: font.openSansLight,
    color: color.secondaryBG,
    fontSize: 12,
    lineHeight: 14,
  },
  uploadCardContainer: {
    paddingRight: 0,
    paddingLeft: 0,
  },
  uploadButton: {
    backgroundColor: color.primary,
    alignSelf: 'flex-start',
    paddingHorizontal: 18,
    paddingVertical: 6.5,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    position: 'absolute',
    bottom: 0,
  },
  container: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  headerContainer: {
    paddingHorizontal: 20,
  },
  headerText: {
    textTransform: 'capitalize',
  },
  mainContainer: {
    flex: 1,
    marginTop: 7,
  },
  weekListView: {
    marginHorizontal: 20,
    backgroundColor: color.secondaryBG,
    borderRadius: 5,
    height: 86,
    maxHeight: 86,
  },
  arrowView: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    position: 'absolute',
    zIndex: 1,
    right: 15,
    top: 5,
  },
  arrowBtn: {
    height: 25,
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentContainerWeekStyle: {
    flexGrow: 1,
  },
  sessionDetail: {
    marginHorizontal: 20,
    marginTop: 28,
  },
  sessionText: {
    fontFamily: font.openSansMedium,
    fontSize: 20,
    color: color.primaryText,
  },
  inputContainer: {
    borderWidth: 0,
    backgroundColor: color.secondaryBG,
    height: 36,
    borderRadius: 5,
  },
  errorLabelStyle: {
    marginTop: 68,
  },
  labelText: {
    fontSize: 15,
    fontFamily: font.openSansMedium,
    color: color.primaryText,
  },
  lableRowStyle: {
    marginBottom: 10,
  },
  optionalText: {
    fontFamily: font.openSansLight,
  },
  introVideoView: {
    marginTop: 3,
  },
  introUpload: {
    marginTop: 10,
  },
  uploadCard: {
    height: 116,
    maxHeight: 116,
    backgroundColor: color.secondaryBG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadDes: {
    fontFamily: font.openSansRegular,
    fontSize: 10,
    color: color.secondaryText,
    textAlign: 'center',
  },
  introVideo: {
    width: '100%',
    height: 198,
    borderRadius: 5,
  },
  btnView: {
    marginVertical: 30,
    backgroundColor: color.primaryBG,
    marginHorizontal: 68,
  },
  exerciseContainer: {
    // marginBottom: 20,
    marginTop: 23,
  },
  buttonView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supersetBtn: {
    borderWidth: 1,
    borderColor: color.primary,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 14,
  },
  removeBtn: {
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 14,
    backgroundColor: color.primary,
  },
  btnRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnTitle: {
    fontFamily: font.openSansMedium,
    lineHeight: 16,
    fontSize: 14,
    color: color.primary,
    marginRight: 10,
  },
  removeBtnTitle: {
    fontFamily: font.openSansMedium,
    lineHeight: 16,
    fontSize: 14,
    color: color.secondaryBG,
    marginRight: 10,
  },
  exerciseCard: {
    marginTop: 23,
    justifyContent: 'center',
    alignItems: 'center',
    height: 120,
    maxHeight: 120,
    borderRadius: 5,
    backgroundColor: color.deactivatedBG,
  },
  error: {
    height: 20,
  },
  exerciseCardText: {
    fontFamily: font.openSansMedium,
    fontSize: 15,
    color: color.secondaryText,
  },
  exerciseList: {
    marginTop: 14,
  },
  dragContentContainer: {
    rowGap: 18,
    flexGrow: 1,
  },
  supersetList: {
    marginTop: 36,
    borderWidth: 1,
    borderColor: color.primary,
    borderRadius: 10,
    padding: 10,
  },
  header: {
    paddingHorizontal: 3,
    marginTop: -22,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 11,
  },
  headingText: {
    fontFamily: font.openSansBold,
    fontSize: 15,
    color: color.primary,
    backgroundColor: color.primaryBG,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
  },
  headingHamburg: {
    backgroundColor: color.primaryBG,
    paddingHorizontal: 8,
  },

  //

  lable: {
    marginBottom: 10,
    fontFamily: font.workSansRegular,
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 17.6,
    color: color.primaryText,
  },
  optionalLable: {
    fontFamily: font.workSansRegular,
    fontWeight: '300',
    fontSize: 15,
    lineHeight: 17.6,
    color: color.primaryText,
  },
  closeImgVideo: {
    backgroundColor: color.transparentColor,
    position: 'absolute',
    right: 80,
    top: 280,
  },
  closeImgVideoSummary: {
    backgroundColor: color.transparentColor,
    position: 'absolute',
    right: 80,
    bottom: 80,
  },
  videoStyle: {
    width: '100%',
    height: 120,
  },
  headerContainerStyle: {
    paddingTop: 14,
    paddingBottom: 6,
    backgroundColor: color.primaryBG,
  },
  screenBackgroundContainerStyle: {
    backgroundColor: color.primaryBG,
  },
  container1: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  contentContainers: {
    flex: 1,
    marginTop: 20,
  },
  ContentManageContainers: {
    flex: 1,
    marginTop: 20,
  },
  weekMainView: {
    height: 86,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    marginBottom: 26,
    paddingVertical: 10,
    borderRadius: 5,
  },
  weekMainShowSessionView: {
    height: 80,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    padding: 5,
    borderBottomWidth: 1,
    borderColor: color.buttonBG,
  },
  weekRemoveBorderSessionView: {
    height: 80,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    padding: 5,
  },
  weekTextStyle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16.34,
    fontFamily: font.openSansRegular,
    marginBottom: 10,
    flex: 1,
    color: color.primaryText,
  },

  imageUploadContanier: {
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    paddingVertical: 20,
    alignItems: 'center',
    borderRadius: 5,
  },

  optionalTextStyle: {
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '300',
  },
  imageUploadRowViewStyle: {
    flexDirection: 'row',
    marginTop: 10,
  },
  videoUploadContanier: {
    backgroundColor: color.secondaryBG,
    width: '100%',
    alignItems: 'center',
    borderRadius: 5,
    height: 116,
    justifyContent: 'center',
  },
  uploadTextRegular: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 11,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginTop: 3,
  },
  weekRowViewManage: {
    flexDirection: 'row',
  },
  clipText: {
    fontSize: 14,
    lineHeight: 16,
    color: color.primary,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
  },
  clipContainer: {
    borderColor: color.primary,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginLeft: 0,
    paddingRight: 9,
  },
  exerciseView: {
    height: 120,
    backgroundColor: color.buttonBG,
    marginTop: 23,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseAddView: {
    height: 88,
    backgroundColor: color.buttonBG,
    marginTop: 22,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseTextStyle: {
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 18,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
  },
  summaryViewStyle: {
    marginTop: 23,
    marginBottom: 25,
  },
  bottonView: {
    marginTop: 9,
    marginBottom: 32,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 23,
  },
  weekConditionTextStyle: {
    fontSize: 20,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    lineHeight: 23,
    fontWeight: '400',
  },
  blackViewMain: {
    height: 40,
    backgroundColor: color.secondaryBG,
    marginTop: 14,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  blackTextStyle: {
    lineHeight: 30,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    marginLeft: 10,
    color: color.primaryText,
    flex: 1,
    fontWeight: '400',
  },
  hamburgIconStyle: {
    marginLeft: 10,
  },
  coachInstructionsViewStyle: {
    height: 136,
    backgroundColor: color.secondaryBG,
    marginTop: 9,
    paddingVertical: 5,
    marginBottom: 6,
  },
  coachTitleStyle: {
    flex: 1,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    lineHeight: 18,
    color: color.primaryText,
    fontWeight: '600',
  },
  rowView: {
    flexDirection: 'row',
  },
  wordTitleStyle: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.lightgray,
    fontWeight: '400',
  },
  inputTitleStyle: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginTop: 5,
  },
  tableViewStyle: {
    height: 59,
    backgroundColor: color.black,
    flexGrow: 1,
    paddingHorizontal: 5,
  },
  tableTextSecStyle: {
    backgroundColor: color.secondaryBG,
    marginBottom: 3,
    borderRadius: 2,
    color: color.primaryText,
    padding: 0,
    paddingLeft: 5,
    width: 83,
  },
  clipOpenTextStyle: {
    color: color.secondaryBG,
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 16,
  },
  clipAddNewTextStyle: {
    color: color.secondaryBG,
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 18,
  },
  clipOpenStyle: {
    height: 30,
    borderRadius: 5,
    width: 175,
    backgroundColor: color.primary,
    alignItems: 'center',
    borderColor: color.primary,
    marginLeft: 0,
    marginTop: 15,
  },
  mainBorderStyle: {
    borderWidth: 1,
    borderColor: color.primary,
    marginTop: 32,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingBottom: 17,
  },
  borderStylePosition: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 1,
    top: -11,
    left: 10,
  },
  borderTitleStyle: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primary,
    backgroundColor: color.primaryBG,
    paddingHorizontal: 5,
    fontWeight: '700',
  },
  iconPositionChangeHandler: {
    justifyContent: 'flex-end',
    flex: 1,
    flexDirection: 'row',
  },
  iconManageColor: {
    backgroundColor: color.primaryBG,
    paddingHorizontal: 10,
  },
  marginStyleTop: {
    marginTop: 10,
  },
  newSessionViewStyle: {
    flexDirection: 'row',
    marginTop: 29,
    marginBottom: 23,
  },
  weekDayTextStyle: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    flex: 1,
    fontWeight: '600',
    marginTop: 20,
  },
  sessionShowCardStyle: {
    height: 45,
    backgroundColor: color.secondaryBG,
    marginBottom: 10,
    borderRadius: 5,
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  sessionCardText: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    flex: 1,
    fontWeight: '400',
  },
  showBottomCardStyle: {
    height: 45,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 25,
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: color.buttonBG,
  },
  showOptionBottom: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginLeft: 6,
    fontWeight: '400',
  },

  borderVideoShowStyle: {
    borderRadius: 10,
  },
  uploadVideoShowStyle: {
    height: 198,
    backgroundColor: color.buttonBG,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 18,
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
  },
  uploadTagViewStyle: {
    height: 22,
    paddingLeft: 17,
    flexDirection: 'row',
    backgroundColor: color.primary,
    alignItems: 'center',
    paddingRight: 14,
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
  },
  uploadTagText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '300',
    fontFamily: font.openSansRegular,
    marginLeft: 3,
    color: color.secondaryBG,
  },
  publishButtonStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
    marginHorizontal: 20,
    marginTop: 20,
  },
  bottomMenuSheetContainer: {
    height: 135,
    paddingBottom: 30,
  },
  ratioTextStyle: {
    marginTop: 3,
  },
  uploadVideoRatioStyle: {
    height: 120,
  },
  uploadVideoSummaryStyle: {
    height: 116,
  },
  imageUploadContainerStyle: {
    paddingHorizontal: 0,
    marginTop: 0,
    backgroundColor: 'red',
  },
  flexRowBottomSheetStyle: {
    flexDirection: 'row',
  },
  selectOptionBottomSheetStyle: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    color: color.secondaryText,
  },
  selectActiveOptionBottomSheetStyle: {
    fontSize: 16,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    color: color.black,
  },
  bottomSheetList: {
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderWidth: 1,
    paddingTop: 41,
    paddingBottom: 34,
  },
  bottomSheetContainer: {
    flex: 1,
  },
  saveButtonStyle: {
    width: 166,
    backgroundColor: color.secondaryBG,
    borderWidth: 1,
    borderColor: color.primary,
  },
  reviewButtonStyle: {
    width: 166,
    backgroundColor: color.lightgray,
  },
  saveButtonTextStyle: {
    color: color.primary,
  },
  reviewButtonTextStyle: {
    color: color.primaryText,
  },
});

export default styles;
