export const referralManagementList = [
  {
    id: 1,
    referralCode: 'SUPERSAVER',
    referredBy: 'John Warner',
    noOfSubs: '35,000',
    conversionRate: '10%',
    revenueGenerated: '$23,548',
    discount: '15%',
  },
  {
    id: 2,
    referralCode: 'FRIENDLY10',
    referredBy: 'Jane Smith',
    noOfSubs: '28,000',
    conversionRate: '8%',
    revenueGenerated: '$18,542',
    discount: '20%',
  },
  {
    id: 3,
    referralCode: 'POWERUSER',
    referredBy: 'Bob Johnson',
    noOfSubs: '42,000',
    conversionRate: '12%',
    revenueGenerated: '$31,245',
    discount: '10%',
  },
  {
    id: 4,
    referralCode: 'NEWBIE',
    referredBy: 'Alice Davis',
    noOfSubs: '15,000',
    conversionRate: '5%',
    revenueGenerated: '$7,546',
    discount: '25%',
  },
  {
    id: 5,
    referralCode: 'VIP',
    referredBy: 'Charlie Brown',
    noOfSubs: '50,000',
    conversionRate: '15%',
    revenueGenerated: '$45,678',
    discount: '5%',
  },
  {
    id: 6,
    referralCode: 'STANDARD',
    referredBy: 'David Williams',
    noOfSubs: '20,000',
    conversionRate: '7%',
    revenueGenerated: '$12,345',
    discount: '15%',
  },
  {
    id: 7,
    referralCode: 'PREMIUM',
    referredBy: 'Eva Garcia',
    noOfSubs: '30,000',
    conversionRate: '9%',
    revenueGenerated: '$27,456',
    discount: '10%',
  },
  {
    id: 8,
    referralCode: 'BASIC',
    referredBy: 'Frank Miller',
    noOfSubs: '10,000',
    conversionRate: '4%',
    revenueGenerated: '$4,321',
    discount: '20%',
  },
  {
    id: 9,
    referralCode: 'ULTIMATE',
    referredBy: 'Grace Wilson',
    noOfSubs: '60,000',
    conversionRate: '18%',
    revenueGenerated: '$67,890',
    discount: '5%',
  },
  {
    id: 10,
    referralCode: 'PRO',
    referredBy: 'Hannah Lewis',
    noOfSubs: '55,000',
    conversionRate: '16%',
    revenueGenerated: '$56,789',
    discount: '10%',
  },
];