export default {
  invalidEmail: 'Please enter valid email/email ID/email address',
  invalidPassword: 'Please enter strong password (Ex. Abcd@123)',
  invalidOldPassword: 'Please enter valid old password (Ex. Abcd@123)',
  invalidNewPass: 'Please enter strong new password (Ex. Abcd@123)',
  invalidOtp: `The code you've entered is incorrect`,
  invalidFirstName: 'Please use only Alphabets characters',
  invalidLastName: 'Please use only Alphabets characters',
  invalidDateOfBirth: 'Not eligible.',
  invalidEducation: 'Please enter a valid education.',
  invalidExperience: 'Please select a valid experience.',
  invalidLocation: 'Please select a valid location.',
  invalidInstagram: 'Please enter a valid instagram id.',
  invalidTiktok: 'Please enter a valid tiktok id.',
  invalidYoutube: 'Please enter a valid youtube channel name.',
  invalidAbout: 'Please enter a valid about us.',
  invalidConfirmPass: 'The passwords do not match',
  invalidForgetPassword: `User doesn't exist`,
  invalidExerciseName: 'Please enter a valid exercise name.',
  invalidCoachInstructions: 'Please enter a valid coach instructions.',
  invalidPackageName: 'Please enter valid Package Name',
  invalidProgramName: 'Please enter valid Program Name',
  invalidDiscount: 'Please enter a valid discount percentage.',
  invalidReferredBy: 'Please enter a valid name',
  emptyWorkoutType: 'Please select workout type',
  emptyLevelOfDifficulty: 'Please select level of difficulty',
  emptyNumberOfWeeks: 'Please select no. of weeks',
  emptyLanguage: 'Please select language',
  emptySquareThumbnail: 'Please upload square thumbnail',
  emptyRectangularThumbnail: 'Please upload rectangular thumbnail',
  emptySessionName: 'Please enter session name.',
  emptyExercise: 'Please select New Exercise.',
  invalidAmount: 'Please enter valid amount.',
};
