import color from '@theme/color';
import font from '@theme/font';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    backgroundColor: color.primaryBG,
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
  headerContainerStyle: {
    paddingTop: 14,
    paddingBottom: 8,
  },
  contentContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  inputContentContainers: {
    flex: 1,
    marginBottom: 50,
  },
  bgImageStyle: {
    height: 221,
    width: '100%',
  },
  viewUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.secondaryBG,
    borderRadius: 24,
    marginTop: 15,
    alignSelf: 'flex-end',
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: color.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  VideoUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.deepPurpleColor,
    borderRadius: 24,
    marginTop: 10,
    marginRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 15,
  },

  videoUserText: {
    fontSize: 13,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    flex: 1,
    fontWeight: '400',
  },
  manageViewSpaceStyle: {
    justifyContent: 'space-between',
    flex: 1,
    flexDirection: 'row',
  },
  managePlayViewSpaceStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  VideoPositionViewShow: {
    height: 29,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: color.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  VideoPositionTextShow: {
    color: color.secondaryBG,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
  },
  backStyle: {
    paddingLeft: 13,
    marginTop: 10,
  },
  likeRowViewManage: {
    flexDirection: 'row',
    marginTop: 10,
  },
  likeViewStyle: {
    marginRight: 12,
  },
  shareViewStyle: {
    marginRight: 20,
  },
  followerShowView: {
    flexDirection: 'row',
    marginBottom: 14,
    marginLeft: 20,
  },
  priceContainer: {
    borderRadius: 27,
    backgroundColor: color.secondaryBG,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 11,
    padding: 4,
    marginRight: 14,
    height: 19,
  },
  priceText: {
    fontFamily: font.openSansRegular,
    fontSize: 12,
    paddingRight: 4,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 14,
    paddingLeft: 2,
  },
  platStyleView: {
    height: 69,
    backgroundColor: color.primary,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  platStyleTitleText: {
    fontSize: 18,
    fontFamily: font.workSansRegular,
    color: color.secondaryBG,
    fontWeight: '500',
    lineHeight: 21,
  },
  platStyleDescriptionText: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    marginTop: 7,
    fontWeight: '500',
  },
  englishViewStyle: {
    height: 29,
    backgroundColor: color.deepPurpleColor,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  weekTextsStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    marginHorizontal: 5,
    fontWeight: '400',
  },
  userCardViewStyle: {
    marginTop: 18,
    height: 59,
    backgroundColor: color.primaryBG,
    borderRadius: 5,
    marginHorizontal: 20,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: color.lightgray,
    marginBottom: 17,
  },
  userImageStyle: {
    height: 49,
    width: 49,
  },
  userNameText: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginBottom: 5,
    fontWeight: '600',
    lineHeight: 20,
  },
  userSubcribersText: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 12,
  },
  userTextRowView: {
    flex: 1,
    marginLeft: 10,
  },
  titleRowViewStyle: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  fullTitle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginLeft: 10,
    fontWeight: '400',
  },
  horizontalStyle: {
    paddingHorizontal: 20,
    paddingBottom: 7,
    borderBottomWidth: 1,
    borderBottomColor: color.buttonBG,
  },
  detailsTextStyle: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    marginTop: 10,
    marginBottom: 6,
    color: color.primaryText,
    fontWeight: '500',
  },
  decriptionTextStyle: {
    fontSize: 11,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 15,
  },
  topContantFlatist: {
    marginHorizontal: 20,
  },
  rowTextPicks: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    lineHeight: 18,
    fontWeight: '500',
    marginHorizontal: 20,
    marginTop: 22,
    marginBottom: 23,
  },
  reviewsStyle: {
    marginTop: 28,
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginHorizontal: 20,
    fontWeight: '500',
    lineHeight: 18,
  },
  ratingViewStyle: {
    fontFamily: font.openSansRegular,
    fontSize: 8,
    color: color.primaryText,
    textAlign: 'center',
    marginBottom: 21,
    fontWeight: '400',
  },
  reviewRowView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  reviewTextStyle: {
    marginLeft: 7,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    lineHeight: 20,
    fontWeight: '700',
  },
  ratingTextStyle: {
    marginLeft: 4,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginRight: 2,
    fontWeight: '500',
    lineHeight: 20,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 5,
    marginHorizontal: 20,
  },
  detailsBottomBorderStyle: {
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: color.buttonBG,
  },
  buttonContainerStyles: {
    marginTop: 12,
    marginBottom: 20,
  },
  cardSimilarManageStyle: {
    paddingHorizontal: 9,
  },
  viewContainerStyles: {
    backgroundColor: color.primaryBG,
    flex: 1,
  }
});

export default styles;
