import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    height: 220,
    width: 260,
  },
  bgImage: {
    flex: 1,
    height: 220,
    width: 260,
    overflow: 'hidden',
  },
  tagView: {
    marginTop: 23,
    height: 23,
    backgroundColor: color.primary,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingTop: 3,
    paddingBottom: 2,
  },
  tagText: {
    fontFamily: font.workSansMedium,
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 17.6,
    textTransform: 'uppercase',
    color: color.secondaryBG,
  },
  detailsView: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  subcriberView: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  ratingCard: {
    paddingHorizontal: 5.29,
    paddingVertical: 1.51,
    backgroundColor: color.secondaryBG,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
  },
  ratingText: {
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 13.62,
    color: color.primaryText,
  },
  ratingIcon: {
    paddingLeft: 2,
  },
  subscriberCard: {
    marginLeft: 10.71,
    paddingHorizontal: 5.29,
    paddingVertical: 1.51,
    backgroundColor: color.secondaryBG,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
  },
  blurCard: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: color.transparentColor,
  },
  infoView: {
    flex: 1,
  },
  titleText: {
    fontFamily: font.workSansMedium,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 14,
    color: color.deactivatedBG,
    textTransform: 'uppercase',
  },
  durationText: {
    marginTop: 2,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 13.62,
    color: color.deactivatedBG,
    textTransform: 'capitalize',
  },
  nameText: {
    marginTop: 2,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 13.62,
    color: color.deactivatedBG,
    textTransform: 'capitalize',
  },
  addToCardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 14,
    backgroundColor: color.deactivatedBG,
    borderRadius: 30,
    paddingTop: 4,
    paddingLeft: 5,
    paddingRight: 13,
    paddingBottom: 4,
    height: 31,
  },
  cartIcon: {
    height: 23,
    width: 23,
    borderRadius: 50,
    backgroundColor: color.primaryText,
    justifyContent: 'center',
    alignItems: 'center',
  },
  priceText: {
    marginLeft: 4,
    fontFamily: font.openSansSemiBold,
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 13.62,
    color: color.primaryText,
  },
});
