import color from '@theme/color';
import font from '@theme/font';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 0,
  },
  keyBoardView: {
    flex: 1,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 0,
  },

  inputContentContainers: {
    flex: 1,
    marginBottom: 50,
  },
  bgImageStyle: {
    height: 221,
    width: '100%',
  },
  viewUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.secondaryBG,
    borderRadius: 24,
    marginTop: 15,
    alignSelf: 'flex-end',
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: color.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  VideoUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.deepPurpleColor,
    borderRadius: 24,
    marginTop: 10,
    marginRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  viewUserText: {
    fontSize: 13,
    fontFamily: font.workSansMedium,
    color: color.primary,
    marginRight: 10,
  },
  videoUserText: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    flex: 1,
    fontWeight: '400',
  },
  manageViewSpaceStyle: {
    justifyContent: 'space-between',
    flex: 1,
    flexDirection: 'row',
  },
  managePlayViewSpaceStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  VideoPositionViewShow: {
    height: 29,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: color.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  VideoPositionTextShow: {
    color: color.secondaryBG,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
  },
  backStyle: {
    paddingLeft: 13,
    marginTop: 10,
  },
  likeRowViewManage: {
    flexDirection: 'row',
    marginTop: 10,
  },
  likeViewStyle: {
    marginRight: 12,
  },
  shareViewStyle: {
    marginRight: 20,
  },
  followerShowView: {
    flexDirection: 'row',
    marginBottom: 14,
    marginLeft: 20,
  },
  priceContainer: {
    borderRadius: 27,
    backgroundColor: color.secondaryBG,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 11,
    paddingHorizontal: 6,
    paddingVertical: 1,
    marginRight: 14,
    height: 19,
  },
  priceText: {
    fontFamily: font.openSansRegular,
    fontSize: 10,
    paddingRight: 4,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 14,
    paddingLeft: 2,
  },
  platStyleView: {
    height: 69,
    backgroundColor: color.primary,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  platStyleTitleText: {
    fontSize: 18,
    fontFamily: font.workSansRegular,
    color: color.secondaryBG,
    fontWeight: '500',
    lineHeight: 21,
  },
  platStyleDescriptionText: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    fontWeight: '500',
    lineHeight: 14,
    marginTop: 7,
  },
  englishViewStyle: {
    height: 29,
    backgroundColor: color.deepPurpleColor,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  weekTextsStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    flex: 1,
    fontWeight: '400',
  },
  englishTextStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    fontWeight: '700',
  },
  userCardViewStyle: {
    marginTop: 18,
    height: 59,
    backgroundColor: color.priceTagBG,
    borderRadius: 5,
    marginHorizontal: 20,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: color.lightgray,
    marginBottom: 7
  },
  userImageStyle: {
    height: 49,
    width: 49,
  },
  userNameText: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginBottom: 5,
    fontWeight: '600',
    lineHeight: 20,
  },
  userSubcribersText: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 12,
  },
  userTextRowView: {
    flex: 1,
    marginLeft: 10,
  },
  titleRowViewStyle: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 10,
    alignItems: 'center',
  },
  fullTitle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginLeft: 10,
  },
  horizontalStyle: {
    marginHorizontal: 20,
    paddingBottom: 21,
    borderBottomWidth: 0.5,
    borderBlockColor: color.deactivatedBG,
  },
  detailsTextStyle: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    marginTop: 26,
    marginBottom: 6,
    color: color.black,
    fontWeight: '500',
    lineHeight: 18,
  },
  decriptionTextStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    fontWeight: '400',
  },
  topContantFlatist: {
    paddingLeft: 20,
  },
  rowTextPicks: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginTop: 17,
    marginBottom: 18,
    fontWeight: '500',
    marginHorizontal: 20,
  },
  ratingViewStyle: {
    fontFamily: font.openSansRegular,
    fontSize: 8,
    color: color.primaryText,
    textAlign: 'center',
    marginBottom: 21,
  },
  reviewRowView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 5,
  },
  cardBgStyle: {
    backgroundColor: color.transparentPurpleColor,
    height: 73,
  },
  rowViewBorderStyle: {
    flexDirection: 'row',
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: color.secondaryBG,
  },
  activeCardStyle: {
    height: 6,
    width: 6,
    borderRadius: 30,
    backgroundColor: color.paleLavender,
    marginRight: 4,
  },
  deActiveCardStyle: {
    height: 4,
    width: 4,
    borderRadius: 30,
    backgroundColor: color.paleLavender,
    marginRight: 4,
  },
  rowView: {
    marginHorizontal: 20,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 21,
    marginBottom: 14,
  },
  showAllView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  showAllTextStyle: {
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 13.62,
    fontFamily: font.openSansRegular,
    marginRight: 5,
    color: color.primaryText,
  },
  cardManageStyle: {
    marginTop: 0,
    marginBottom: 10,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  cardSimilarManageStyle: {
    marginTop: 0,
    marginBottom: 20,
    paddingHorizontal: 9,
  },
  rowTextHadingPicks: {
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 21.11,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
  },
  packageTagTextStyle: {
    fontSize: 12,
    lineHeight: 14,
  },
  bgCardViewStyle: {
    height: 212,
    width: 212,
  },
  similarCardViewStyle: {
    height: 255,
  },
});

export default styles;
