import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    borderRadius: 5,
  },
  activeContainer: {
    backgroundColor: color.primary,
  },
  headerCard: {
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 11,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkBoxRow: {
    flex: 1,
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  deleteBoxRow: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  checkBoxIcon: {
    height: 15,
    width: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteIcon: {
    height: 18,
    width: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hambirgIcon: {
    marginLeft: 10,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backSquatText: {
    marginLeft: 10,
    fontFamily: font.openSansRegular,
    fontSize: 12,
    color: color.primaryText,
  },
  thumbnailView: {
    marginTop: 20,
    height: 198,
    width: '100%',
    backgroundColor: color.deactivatedBG,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 1.5,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  thumbnail: {
    flex: 1,
    height: 198,
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  thumbnailImage: {
    height: 198,
    width: '100%',
    justifyContent: 'flex-end',
  },
  uploadButton: {
    position: 'absolute',
    backgroundColor: color.primary,
    alignSelf: 'flex-start',
    paddingHorizontal: 18,
    paddingVertical: 6.5,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  uploadVideoText: {
    marginLeft: 6,
    fontFamily: font.openSansLight,
    color: color.secondaryBG,
    fontSize: 12,
    lineHeight: 14,
  },
  instructionView: {
    marginTop: 8,
    backgroundColor: color.secondaryBG,
    height: 136,
    maxHeight: 136,
    width: '100%',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  instructionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  instructionTitle: {
    fontFamily: font.openSansSemiBold,
    fontSize: 12,
    lineHeight: 18,
    color: color.primaryText,
  },
  count: {
    fontFamily: font.openSansRegular,
    fontSize: 10,
    color: color.secondaryText,
  },
  instructionValue: {
    marginTop: 10,
    fontFamily: font.openSansRegular,
    fontSize: 10,
    color: color.secondaryText,
  },
  metricView: {
    backgroundColor: color.primaryText,
    height: 53,
    width: '100%',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setsRow: {
    // flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginRight: 7,
  },
  setHeadingText: {
    fontFamily: font.openSansRegular,
    fontSize: 12,
    color: color.secondaryBG,
  },
  setsCard: {
    marginTop: 3.5,
    paddingVertical: 3.64,
    backgroundColor: color.secondaryBG,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  setNumberView: {
    width: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  isSetNumberView: {
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setNumberText: {
    width: 26,
    fontFamily: font.openSansRegular,
    fontSize: 15,
    color: color.primaryText,
  },
  verticalLine: {
    height: 16,
    width: 0.5,
    backgroundColor: color.primaryText,
  },
  setStringView: {
    width: 31,
    justifyContent: 'center',
    alignItems: 'center',
  },
  isSetStringView: {
    width: 29,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setStringText: {
    fontFamily: font.openSansRegular,
    fontSize: 10,
    color: color.primaryText,
  },
});
