export const myPackagesData = [
  {
    id: 1,
    tag: 'Crossfit',
    title: 'Bodyweight only beginner',
    followers: '16k',
    level: 'Intermediator',
    rating: '4.5',
    duration: '12 week',
    progress: '90%',
  },
  {
    id: 2,
    tag: 'Crossfit',
    title: 'Bodyweight only beginner',
    followers: '16k',
    level: 'Intermediator',
    rating: '4.5',
    duration: '12 week',
    progress: '90%',
  },
  {
    id: 3,
    tag: 'Crossfit',
    title: 'Bodyweight only beginner',
    followers: '16k',
    level: 'Intermediator',
    rating: '4.5',
    duration: '12 week',
    progress: '90%',
  },
  {
    id: 4,
    tag: 'Crossfit',
    title: 'Bodyweight only beginner',
    followers: '16k',
    level: 'Intermediator',
    rating: '4.5',
    duration: '12 week',
    progress: '90%',
  },
  {
    id: 5,
    tag: 'Crossfit',
    title: 'Bodyweight only beginner',
    followers: '16k',
    level: 'Intermediator',
    rating: '4.5',
    duration: '12 week',
    progress: '90%',
  },
];
