import color from '@theme/color';
import font from '@theme/font';
import {percentageHeight} from '@utility/functions/dimensionsScale';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentWrapper: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: color.primaryBG,
  },
  headingView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headingText: {
    flex: 1,
    fontFamily: font.workSansMedium,
    fontSize: 20,
    lineHeight: 23.46,
    color: color.primaryText,
  },
  threeDotIcon: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 5,
  },
  rbsheetStyle: {
    backgroundColor: color.transparent,
  },
  headerLableStyle: {
    fontFamily: font.workSansRegular,
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 23,
    color: color.primaryText,
  },
  screenBackgroundContainerStyle: {
    backgroundColor: color.primaryBG,
    paddingHorizontal: 0,
  },
  headerContainerStyle: {
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: color.primaryBG,
  },
  searchContainerStyle: {
    marginTop: 30,
    marginBottom: 20,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: color.primaryBG,
    paddingHorizontal: 18,
  },
  listView: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    paddingBottom: 38,
    marginTop: 10,
    rowGap: 6,
  },
  footerCom: {
    marginBottom: 30,
  },
  btnRowView: {
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  btnOutlineStyle: {
    flex: 1,
    height: 40,
    backgroundColor: color.primaryBG,
    borderWidth: 1,
    borderColor: color.primary,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
  },
  btnOutlineText: {
    marginLeft: 7,
    color: color.primary,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
    fontSize: 11.4,
    lineHeight: 14,
  },
  btnSolidStyle: {
    marginLeft: 15,
    flex: 1,
    height: 40,
    backgroundColor: color.primary,
    borderWidth: 1,
    borderColor: color.primary,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
  },
  btnSolidText: {
    marginLeft: 7,
    color: color.secondaryBG,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
    fontSize: 11.4,
    lineHeight: 14,
  },
  modalContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalInnerContainer: {
    width: 315,
    backgroundColor: color.secondaryBG,
    borderRadius: 10,
    paddingVertical: 20,
  },
  imageStyle: {
    alignSelf: 'center',
  },
  modalTitleText: {
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalDesText: {
    marginTop: 31,
    paddingHorizontal: 46,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalDescriptionText: {
    marginTop: 10,
    paddingHorizontal: 13,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalDestTitleText: {
    marginTop: 31,
    paddingHorizontal: 46,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  btnView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    backgroundColor: color.primaryBG,
  },
  btnContainer: {
    width: 114,
    backgroundColor: color.lightgray,
    height: 39,
    borderRadius: 10,
    marginTop: 0,
    paddingTop: 0,
  },
  btnCancelContainer: {
    width: 114,
    backgroundColor: color.warning,
    height: 39,
    borderRadius: 10,
    marginTop: 0,
    paddingTop: 0,
  },
  nameTextStyle: {
    fontSize: 14,
    color: color.secondaryBG,
    lineHeight: 19,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
  },
  nameTextButtonCancelStyle: {
    fontSize: 14,
    color: color.primaryText,
    lineHeight: 19,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
  },
  bottomSheetContainer: {
    height: 280,
  },
  headerLabelStyle: {
    fontSize: 20,
    lineHeight: 23,
    fontWeight: '500',
    color: color.primaryText,
  },
  searchStyle: {
    height: 36,
  },
  searchFilterStyle: {
    height: 36,
    width: 36,
  },
  cardTitleStyle: {
    letterSpacing: 1,
  },
  cancelBtnStyle: {
    borderColor: color.primary,
    marginRight: 10,
    width: '90%',
    backgroundColor: color.secondaryBG,
    borderWidth: 1,
  },
  cancelBtnText: {
    color: color.primary,
    fontSize: 14,
    lineHeight: 17,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
  },
  createPackagesBtnStyle: {
    width: '80%',
  },
  createPackagesStyle: {
    color: color.secondaryBG,
    fontSize: 14,
    lineHeight: 17,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
  },
  sessionMainView: {
    height: percentageHeight(39.5),
    backgroundColor: color.paleLavender,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: percentageHeight(0.5),
    marginTop: percentageHeight(3.4),
  },
  createNewProgramsText: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: percentageHeight(1.4),
    lineHeight: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginTop: 12,
    marginHorizontal: percentageHeight(10.7),
  },
  createNewProgramsSelectText: {
    fontWeight: '600',
    color: color.primary,
  },
  editModal: {
    backgroundColor: color.transparent,
    alignItems: 'center',
  },
  editModalMainContainer: {
    backgroundColor: color.secondaryBG,
    padding: 21,
    width: '80%',
    borderRadius: 10,
  },
  editModalIcon: {
    paddingVertical: 12,
    paddingHorizontal: 7,
    alignSelf: 'center',
    marginBottom: 22,
  },
  editModalDes: {
    fontFamily: font.openSansRegular,
    fontSize: 14,
    lineHeight: 16,
    color: color.primaryText,
    textAlign: 'center',
  },
  editModalDesContinue: {
    marginTop: 15,
    fontFamily: font.openSansRegular,
    fontSize: 14,
    lineHeight: 16,
    color: color.primaryText,
    textAlign: 'center',
  },
  editModalBtn: {
    marginTop: 22,
    paddingHorizontal: 17,
    flexDirection: 'row',
    alignItems: 'center',
  },
  editModalBtnView: {
    flex: 1,
    alignItems: 'center',
  },
  editModalCancelBtnView: {
    marginLeft: 10,
  },
  editModalYesBtn: {
    backgroundColor: color.lightgray,
    height: 39,
    borderRadius: 10,
    paddingHorizontal: 45,
  },
  editModalYesBtnText: {
    fontSize: 14,
    color: color.primaryText,
    lineHeight: 19,
    fontFamily: font.openSansSemiBold,
    fontWeight: '600',
  },
  editModalCancelBtn: {
    backgroundColor: color.primary,
    height: 39,
    borderRadius: 10,
    paddingHorizontal: 34.5,
  },
  editModalCancelBtnText: {
    fontSize: 14,
    color: color.secondaryBG,
    lineHeight: 19,
    fontFamily: font.openSansSemiBold,
    fontWeight: '600',
  },
  handleStyle: {
    height: 0,
    paddingTop: 0,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: color.secondaryBG,
  },
  handleIndicatorStyle: {
    display: 'none',
  },
  backgroundStyle: {
    backgroundColor: color.secondaryBG,
  },
});

export default styles;
